//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDR_Types_Paiement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDR_Types_Paiement()
        {
            this.MDR_Paiement = new HashSet<MDR_Paiement>();
        }
    
        public int TPai_Index { get; set; }
        public string TPai_Nom { get; set; }
        public Nullable<int> TPai_Actif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDR_Paiement> MDR_Paiement { get; set; }
    }
}
