//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDR_Fournisseurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDR_Fournisseurs()
        {
            this.MDR_Sites = new HashSet<MDR_Sites>();
            this.MDR_Composants = new HashSet<MDR_Composants>();
        }
    
        public int Four_Index { get; set; }
        public string Four_Nom { get; set; }
        public Nullable<int> Four_Actif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDR_Sites> MDR_Sites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDR_Composants> MDR_Composants { get; set; }
    }
}
